# Generated by Django 6.0 on 2026-01-05 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BCA', 'BCA'), ('BSC_CS', 'BSc Computer Science'), ('BSC_IT', 'BSc Information Technology'), ('BCOM', 'BCom'), ('BA', 'BA')], max_length=20)),
                ('semester', models.PositiveIntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, '3rd Semester'), (4, '4th Semester'), (5, '5th Semester'), (6, '6th Semester')], default=1)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('register_number', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
