# Generated by Django 6.0 on 2025-12-22 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=20, unique=True)),
                ('parent_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('course', models.CharField(choices=[('BCA', 'BCA'), ('BSC_CS', 'BSc Computer Science'), ('BSC_IT', 'BSc Information Technology'), ('BCOM', 'BCom'), ('BA', 'BA')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
