# Generated by Django 6.0 on 2026-01-11 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_user_alter_student_register_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_encoding', models.BinaryField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_data', to='students.student')),
            ],
        ),
    ]
