# Generated by Django 6.0 on 2026-01-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentface'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentface',
            name='face_image',
            field=models.ImageField(blank=True, upload_to='faces/'),
        ),
        migrations.AlterField(
            model_name='studentface',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
