# Generated by Django 6.0 on 2026-01-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
