# Generated by Django 6.0 on 2025-12-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
