# Generated by Django 6.0 on 2025-12-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.PositiveIntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, '3rd Semester'), (4, '4th Semester'), (5, '5th Semester'), (6, '6th Semester')], default=1),
        ),
    ]
