# Generated by Django 6.0 on 2026-01-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='academic_year',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='fee',
            name='semester',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(choices=[('TUITION', 'Tuition Fee'), ('EXAM', 'Exam Fee'), ('SPORTS', 'Sports Fee'), ('HOSTEL', 'Hostel Fee'), ('BUS', 'Bus Fee'), ('LIBRARY', 'Library Fine'), ('ADMISSION', 'Admission Fee')], max_length=50),
        ),
    ]
