# Generated by Django 6.0 on 2026-01-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_fee_academic_year_fee_semester_alter_fee_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(choices=[('TUITION', 'Tuition Fee'), ('EXAM', 'Exam Fee'), ('SPORTS', 'Sports Fee'), ('LIBRARY', 'Library Fine'), ('ADMISSION', 'Admission Fee')], max_length=50),
        ),
    ]
