# Generated by Django 6.0 on 2026-01-08 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_alter_fee_fee_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='academic_year',
        ),
    ]
