# Generated by Django 6.0 on 2026-01-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_remove_fee_academic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, choices=[('BCA', 'BCA'), ('BSC_CS', 'BSc Computer Science'), ('BSC_IT', 'BSc Information Technology'), ('BCOM', 'BCom'), ('BA', 'BA')], help_text='Leave blank to apply fee to all students', max_length=20, null=True)),
                ('fee_type', models.CharField(choices=[('TUITION', 'Tuition Fee'), ('EXAM', 'Exam Fee'), ('SPORTS', 'Sports Fee'), ('LIBRARY', 'Library Fine'), ('ADMISSION', 'Admission Fee')], max_length=50)),
                ('semester', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(max_length=50),
        ),
    ]
