# Generated by Django 6.0 on 2026-01-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_feestructure_alter_fee_fee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='paid_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
