# Generated by Django 6.0 on 2026-01-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_fee_paid_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='paid_by',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('parent', 'Parent')], max_length=10, null=True),
        ),
    ]
