# Generated by Django 6.0 on 2026-01-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_fee_paid_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='semester',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, '3rd Semester'), (4, '4th Semester'), (5, '5th Semester'), (6, '6th Semester')], null=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='semester',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, '3rd Semester'), (4, '4th Semester'), (5, '5th Semester'), (6, '6th Semester')], help_text='Leave blank to apply to all semesters', null=True),
        ),
    ]
