# Generated by Django 6.0 on 2026-02-11 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0009_fee_user_alter_fee_paid_by_alter_fee_student'),
        ('library', '0007_delete_libraryfinepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='library.issue'),
        ),
    ]
