# Generated by Django 6.0 on 2025-12-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('course', models.CharField(choices=[('BCA', 'BCA'), ('BSC_CS', 'BSc Computer Science'), ('BSC_IT', 'BSc Information Technology'), ('BCOM', 'BCom'), ('BA', 'BA')], max_length=20)),
                ('semester', models.PositiveIntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, '3rd Semester'), (4, '4th Semester'), (5, '5th Semester'), (6, '6th Semester')])),
            ],
        ),
    ]
