# Generated by Django 6.0 on 2026-01-01 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
    ]
