# Generated by Django 6.0 on 2026-01-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_remove_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('MATHS', 'Mathematics'), ('PHY', 'Physics'), ('CHEM', 'Chemistry'), ('CS', 'Computer Science'), ('ENG', 'English'), ('ML', 'Malayalam'), ('CM', 'Commerse'), ('FN', 'Financial')], max_length=20),
        ),
    ]
