# Generated by Django 6.0 on 2026-01-02 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject_text',
            field=models.CharField(choices=[('MATHS', 'Mathematics'), ('PHY', 'Physics'), ('CHEM', 'Chemistry'), ('CS', 'Computer Science'), ('ENG', 'English'), ('ML', 'Malayalam'), ('CM', 'Commerse'), ('FN', 'Financial')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.subject'),
        ),
    ]
