# Generated by Django 6.0 on 2026-01-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teacher_subject_text_alter_teacher_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject_text',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('MATHS', 'Mathematics'), ('PHY', 'Physics'), ('CHEM', 'Chemistry'), ('CS', 'Computer Science'), ('ENG', 'English'), ('ML', 'Malayalam'), ('CM', 'Commerse'), ('FN', 'Financial')], max_length=20, null=True),
        ),
    ]
