# Generated by Django 6.0 on 2026-01-06 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.PositiveIntegerField(default=0)),
                ('test2', models.PositiveIntegerField(default=0)),
                ('assignment', models.PositiveIntegerField(default=0)),
                ('attendance_mark', models.PositiveIntegerField(default=0)),
                ('total_internal', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved')], default='Draft', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.subject')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.timetable')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
