# Generated by Django 6.0 on 2026-02-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_marks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalmark',
            name='semester',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
