# Generated by Django 6.0 on 2026-02-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_marks', '0002_internalmark_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalmark',
            name='semester',
            field=models.PositiveIntegerField(),
        ),
    ]
