# Generated by Django 6.0 on 2026-03-03 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('internal_marks', '0003_alter_internalmark_semester'),
        ('students', '0006_remove_semester_is_active_and_more'),
        ('teachers', '0002_remove_teacher_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='internalmark',
            unique_together={('student', 'subject', 'timetable')},
        ),
        migrations.RemoveField(
            model_name='internalmark',
            name='semester',
        ),
    ]
