# Generated by Django 6.0 on 2026-01-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BCA', 'BCA'), ('BSC_CS', 'BSc Computer Science'), ('BSC_IT', 'BSc Information Technology'), ('BCOM', 'BCom'), ('BA', 'BA')], max_length=20)),
                ('semester', models.PositiveIntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, '3rd Semester'), (4, '4th Semester'), (5, '5th Semester'), (6, '6th Semester')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='UPCOMING', max_length=10)),
            ],
            options={
                'unique_together': {('course', 'semester')},
            },
        ),
    ]
