# Generated by Django 6.0 on 2026-02-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='semester',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
